### ISSUE TITLE
Qt4 is deprecated / EOL, Qt5 doesn't core WebKit anymore

### ISSUE THREAD

**Issue by kernc** [smoqadam/PyFladesk#1]
An aync replacement is Qt WebEngine.

**Comment by MaximilianKindshofer** [comment]
I made a PullRequest adressing the Issue, but I somehow broke the Signal API - now it opens all Links in PyFladesk.

**Comment by smoqadam** [comment]
Thanks @MaximilianKindshofer , I'll check it. But it seems web have a problem in opening external links in outside of app.

**Comment by MaximilianKindshofer** [comment]
Oh, yes I dind't got the Signals right

**Comment by ELC** [comment]
I solve this issue in my PR (#4 ), it also solves #3
