### ISSUE TITLE
Change host?

### ISSUE THREAD

**Issue by husos** [smoqadam/PyFladesk#10]
Hi, i was wondering how could i change host.. Normally we put it in app.run() but now it's replace by init_gui how we do it? I'm trying to get access over my network so 0.0.0.0

Btw i'm not advanced in Python/Flask thanks in advance.

**Comment by ELC** [comment]
You can modify and config your Flask app object before passing it as argument to the init_gui function. In case you need even more customization you can simply download the \_\_init\_\_.py file from this repo and change the app.run invocation to fit your needs.

**Comment by husos** [comment]
Thanks! It's work :)

**Comment by ELC** [comment]
Perfect! I close this issue since it's solved
