### ISSUE TITLE
Add dependency for PyQtWebEngine

### ISSUE THREAD

**Issue by heepdog** [smoqadam/PyFladesk#17]
Installed PyFladesk today and wen I tried to run it.  I received an import error that QtWebEngineWidgets could not be imported.  After installing PyQtWebEngine it ran without errors.

**Comment by enricojr01** [comment]
Seconded. Had the same problem just now, googling brings this up https://pypi.org/project/PyQtWebEngine/, and this thread -> https://askubuntu.com/questions/763612/importerror-no-module-named-pyqt5-qtwebenginewidgets

stating that the QtWebEngineWidgets stuff has been moved to its own, separate package (last answer on the page)

**Comment by ELC** [comment]
Solved in https://github.com/smoqadam/PyFladesk/commit/9821cc537dd33509e430acecb3a671bfa668f5b8
