### ISSUE TITLE
Add Backward Compatibility to PyQt4 and <=PyQt5.6

### ISSUE THREAD

**Issue by ELC** [smoqadam/PyFladesk#5]
I've already create two separated branches for the PyQt4 version and the PyQt5.6 version. The 5.6 is the one with greatest performance since QWebView is still faster than QWebEngineView.

Create two branches in the main repository so I can open a PR. One branch from 8baec2 and another from c44a01

**Comment by smoqadam** [comment]
Thanks for your effort, new branch added.
