### ISSUE TITLE
Internal server error after packaging with pyinstaller

### ISSUE THREAD

**Issue by weirdyang** [smoqadam/PyFladesk#9]
Hi,  
The app works when I run it locally. However once I convert it to an exe using pyinstaller, I get an internal server error. Any ideas on how or where I can start troubleshooting this? First time using pyinstaller.  THanks!

**Comment by ELC** [comment]
Could you please give some more information? Operative System and the output of the console. Check first if it works with one directory mode and the one file and in case of error show us the console

**Comment by weirdyang** [comment]
Hi,  
I'm using windows 10, python3.6.  
The error I get is 'internal server error', I thought it might be because of bad file paths, but I've tried the solution provided in this https://stackoverflow.com/questions/7674790/bundling-data-files-with-pyinstaller-onefile, and it works locally but not in an executable.

I just tried using one directory mode and it works!

**Comment by ELC** [comment]
Internal server error is the one shown in the main window, can you show us the error in the console? The trace of the error.

**Comment by weirdyang** [comment]
Sorry do you mind teaching me how do I check the console for the
executable?

**Comment by ELC** [comment]
Just run pyinstaller without the `w` flag

**Comment by weirdyang** [comment]
Thanks!  This is the traceback. I've added the templates folders using the
add data command.

    [2018-03-09 01:52:37,889] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "site-packages\flask\app.py", line 1982, in wsgi_app
  File "site-packages\flask\app.py", line 1614, in full_dispatch_request
  File "site-packages\flask\app.py", line 1517, in handle_user_exception
  File "site-packages\flask\_compat.py", line 33, in reraise
  File "site-packages\flask\app.py", line 1612, in full_dispatch_request
  File "site-packages\flask\app.py", line 1598, in dispatch_request
  File "app.py", line 25, in index
  File "site-packages\flask\templating.py", line 133, in render_template
  File "site-packages\jinja2\environment.py", line 869, in
get_or_select_template
  File "site-packages\jinja2\environment.py", line 830, in get_template
  File "site-packages\jinja2\environment.py", line 804, in _load_template
  File "site-packages\jinja2\loaders.py", line 113, in load
  File "site-packages\flask\templating.py", line 57, in get_source
  File "site-packages\flask\templating.py", line 85, in _get_source_fast
jinja2.exceptions.TemplateNotFound: index.html
127.0.0.1 - - [09/Mar/2018 01:52:37] "GET / HTTP/1.1" 500 -

**Comment by ELC** [comment]
So either you don't use the --add-data param in the pyinstaller or you have a problem with your templates

**Comment by weirdyang** [comment]
I used the --add-data param as instructed in the readme.md, and the app
works fine in one dir and when I run it from the terminal.

My app.spec:

# -*- mode: python -*-

block_cipher = None


a = Analysis(['app.py'],
             pathex=['C:\\Program Files (x86)\\Windows
Kits\\10\\Redist\\ucrt\\DLLs\\x64',
'C:\\Users\\me\\Desktop\\pythonApp\\webdesk'],
             binaries=[],
             datas=[('templates', 'templates'), ('static', 'static')],
             hiddenimports=['ctypes'],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          name='app',
          debug=False,
          strip=False,
          upx=True,
          runtime_tmpdir=None,
          console=False )

**Comment by smoqadam** [comment]
take a look at [this](https://github.com/smoqadam/PyFladesk-rss-reader/commit/0e552a43d72fdd88ff939b283da05db30fd16dea#diff-e6397cedf9a12c8ce83be07e9320d199R20) it might be helpfull

**Comment by weirdyang** [comment]
Thanks. I tried it, but still no luck. I think it's because pyinstaller does not set the env variable as mentioned in this link: https://stackoverflow.com/questions/7674790/bundling-data-files-with-pyinstaller-onefile  
I'll report back if I figure this out. thanks again for your help.  
  

edit;  Fixed it!!

Include this at the top, under imports

    if getattr(sys, 'frozen', False):
        template_folder =resource_path('templates')
        static_folder = resource_path('static')
        app = Flask(__name__, template_folder=template_folder, static_folder=static_folder)
    else:
        app = Flask(__name__)

Define this in a helper script:  

    def resource_path(relative_path):
     """ Get absolute path to resource, works for dev and for PyInstaller """
        base_path = getattr(sys, '_MEIPASS', os.path.dirname(os.path.abspath(__file__)))
        return os.path.join(base_path, relative_path)   

   
credit to [Jonathon Reinhart](https://stackoverflow.com/questions/7674790/bundling-data-files-with-pyinstaller-onefile/44352931#44352931)  
   
additional notes:  
if building on a windows 10 system use:  
   
    pyinstaller -w -F --add-data "templates;templates" --add-data "static;static" app.py --path 'C:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\x64'

**Comment by ELC** [comment]
Thanks for the comments, I will close the issue since it's solved

**Comment by ELC** [comment]
Readme updated

**Comment by weirdyang** [comment]
btw this is the app I made with pyfladesk; https://github.com/captmomo/drowzee  
thanks again for your help :)
